export const ADD_RECORD = "ADD_RECORD";
export const RETRIVE_RECORDS = "RETRIVE_RECORDS";
export const RETRIVE_SINGLE_RECORD = "RETRIVE_SINGLE_RECORD";
export const CLEAR_SINGLE_RECORD_SELECTION = "CLEAR_SINGLE_RECORD_SELECTION";
export const POST_RECORD_SUCCESSFULL = "POST_RECORD_SUCCESSFULL";
export const CHANGE_SYSTEM_NUMBER_REQUEST = "CHANGE_SYSTEM_NUMBER_REQUEST";
export const CHANGE_SYSTEM_NUMBER_SUCCESS = "CHANGE_SYSTEM_NUMBER_REQUEST_SUCCESS";

// delete the selected record
export const DELETE_SELECTED_RECORD_REQUEST_SUCCESS = "DELETE_SELECTED_RECORD_REQUEST_SUCCESS";

// To register user
export const REGISTER_USER_REQUEST_SUCCESS = "REGISTER_USER_REQUEST_SUCCESS"; 
// login request
export const LOGIN_REQUEST_SUCCESS="LOGIN_REQUEST_SUCCESS";

// Check whether logged in or not
export const USER_LOGGED_IN = "USER_LOGGED_IN";
export const USER_LOGGED_OFF = "USER_LOGGED_OFF";

// Clear Page Level Notifiaction
export const CLEAR_PAGE_LEVEL_NOTIFICATION = "CLEAR_PAGE_LEVEL_NOTIFICATION";

// Redirection
// login
export const REDIRECT_TO_LOGIN = "REDIRECT_TO_LOGIN";
export const CLEAR_REDIRECTION_TO_LOGIN = "CLEAR_REDIRECTION_TO_LOGIN";
// home
export const REDIRECT_TO_HOME = "REDIRECT_TO_HOME";
export const CLEAR_REDIRECTION_TO_HOME = "CLEAR_REDIRECTION_TO_HOME";