export const ADD_RECORD = "ADD_RECORD";
export const RETRIVE_RECORDS = "RETRIVE_RECORDS";
export const RETRIVE_SINGLE_RECORD = "RETRIVE_SINGLE_RECORD";
export const POST_RECORD_SUCCESSFULL = "POST_RECORD_SUCCESSFULL";
export const CHANGE_SYSTEM_NUMBER_REQUEST = "CHANGE_SYSTEM_NUMBER_REQUEST";
export const CHANGE_SYSTEM_NUMBER_SUCCESS = "CHANGE_SYSTEM_NUMBER_REQUEST_SUCCESS";